### ISSUE TITLE
Chrome images cannot be tested using current script

### ISSUE THREAD

**Issue by ruescar** [aerokube/selenoid-images#108]
In 'automate_chrome.sh', tests are not passing because Chrome images don't include Selenoid inside, as opposed to Firefox images, where tests pass. Shouldn't this step run Selenoid container as normal and use a generated browsers.json to load the new built chrome image?
Instead of doing:
```
docker run -d --name selenium -p 4445:4444 $1:$2
mvn clean test -Dgrid.connection.url="http://localhost:4445/" -Dgrid.browser.name=chrome -Dgrid.browser.version=$2 || true
```
I tried something like this (after creating a little template for browsers.json), which worked:

```
cat chrome/browsers.json.tmpl | sed -e "s|@@CHROME_VERSION@@|$tag|g" > "chrome/browsers.json"
docker run -d --name selenium -p 4445:4444 -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/chrome/:/etc/selenoid/:ro aerokube/selenoid:1.9.1
mvn clean test -Dgrid.connection.url="http://localhost:4445/wd/hub" -Dgrid.browser.name=chrome -Dgrid.browser.version=$tag || true
```

**Comment by vania-pooh** [comment]
@ruescar what exactly is not passing? Firefox images have Selenoid inside because Geckodriver does not implement some commonly used APIs like upload files. Chromedriver contrarily implements all required APIs so Selenoid is not needed.

**Comment by ruescar** [comment]
@vania-pooh When the 'container-tests' run at the end of automate_chrome.sh I can see an error in the docker logs of the Chrome browser container (name=selenium) related to DevToolsActivePort that doesn't allow chrome to launch properly.
After searching for this error on Internet, I found a way to make the tests pass, which was adding the following capabilities to the WebDriver client (in the 'container-tests' code):
chromeOptions: {
      args: ['--disable-gpu', '--no-sandbox', '--disable-extensions', '--disable-dev-shm-usage']
    }

**Comment by vania-pooh** [comment]
@ruescar yes, for Chrome all tests pass. However I'm building images under Ubuntu.

**Comment by ruescar** [comment]
Thanks for the clarification @vania-pooh

**Comment by vania-pooh** [comment]
@ruescar glad to hear. Did not test it with Java 11, they are releasing versions too fast. :)
