### ISSUE TITLE
New library needed for building Chrome images from Debian packages

### ISSUE THREAD

**Issue by ruescar** [aerokube/selenoid-images#109]
I think libappindicator3-1 library is required in selenium/chrome/local/Dockerfile for building Chrome images from Debian packages.

**Comment by vania-pooh** [comment]
@ruescar why is that?

**Comment by ruescar** [comment]
@vania-pooh I get the following error when I run this command (after having downloaded the .deb file):
./automate_chrome.sh google-chrome-stable_73.0.3683.86-1_amd64.deb 73.0.3683.68 73.0

Unpacking google-chrome-stable (73.0.3683.86-1) ...
Processing triggers for menu (2.1.47ubuntu1) ...
dpkg: dependency problems prevent configuration of google-chrome-stable:
 google-chrome-stable depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

**Comment by vania-pooh** [comment]
@ruescar ok, proceed with PR then.

**Comment by vania-pooh** [comment]
@ruescar are you building with `3.0.0` tag or master? Could you try to add `libappindicator3-1` to this [file](https://github.com/aerokube/selenoid-images/blob/master/selenium/chrome/local/Dockerfile) and see whether it help. If it does - please proceed with PR then.

**Comment by ruescar** [comment]
@vania-pooh Yes I'm building with tag 3.0.0 and yes the issue is fixed by either adding libappindicator3-1 to the Docker file or replacing libappindicator1 for libappindicator3-1
Unfortunately I'm struggling to build the master branch on a Mac for other reasons, so I'm not confident to create a PR for this. Maybe when tag 4.0.0 is released...

**Comment by vania-pooh** [comment]
@ruescar will be rebuilding images with 4.0.0 soon and will see whether your fix works.

**Comment by ruescar** [comment]
@vania-pooh Any updates on tag 4.0.0release date?

**Comment by vania-pooh** [comment]
@ruescar there will be 5.0.0 release. :) Could you check with latest master whether this package is needed?

**Comment by ruescar** [comment]
@vania-pooh Great! Looking forward to this new version. Especially because of using newer version of Ubuntu. Regarding this issue, there's two libraries that need to be changed. I've opened PR #159

**Comment by vania-pooh** [comment]
@ruescar merged.

**Comment by ruescar** [comment]
With these changes Chrome image builds successfully in Ubuntu 16.04 using latest chrome stable version 75.0.3770.90 (google-chrome-stable_current_amd64.deb).
However selenoid-container-tests throw Errors. On the other hand, no errors are thrown if those tests are run using our develop branch (https://github.com/twilio/selenoid-container-tests) which disables chrome sandbox.
