### ISSUE TITLE
Message: cannot create session firefox-54.0 on any hosts after 15 attempt(s), last host error was: Malformed screenResolution capability: 1920x1080. Correct format is WxHxD, e.g. 1920x1080x24.

### ISSUE THREAD

**Issue by ersuniljoshi** [aerokube/selenoid-images#11]
@aandryashin AS per the discussion creating this issue.

there is still old selenoid version packed into that image, please create issue on github and we will fix it, as workaround set screen resolution to 1920x1080x24…

**Comment by vania-pooh** [comment]
Oh, can certainly repack the image.

**Comment by vania-pooh** [comment]
Updated Selenoid to 1.3.6 in Firefox 53 to 55 images (including VNC ones). Documentation about it was updated in https://github.com/aerokube/selenoid/pull/212.
