### ISSUE TITLE
Firefox is not able to play mp4 files

### ISSUE THREAD

**Issue by Dmitriy85** [aerokube/selenoid-images#110]
In order to have ability to play mp4 video for our tests we need to install additional soft in container:
sudo add-apt-repository ppa:jonathonf/ffmpeg-4
sudo apt-get update
sudo apt-get install ffmpeg

Is it possible to include this software in the image?
I assume that may be needed by many users which have the same case...
Thanks in advance!

**Comment by vania-pooh** [comment]
Need to understand which ffmpeg dependency delivers this.

**Comment by Dmitriy85** [comment]
> Need to understand which ffmpeg dependency delivers this.

Sure, I'll ping you in telegram after find out the dependency name.

**Comment by vania-pooh** [comment]
@Dmitriy85 any updates on this?

**Comment by Dmitriy85** [comment]
> @Dmitriy85 any updates on this?

unfortunalty no for the moment - still in progress.
