### ISSUE TITLE
selenoid/browser_name:latest should point to the latest version of browser image

### ISSUE THREAD

**Issue by vgrigoruk** [aerokube/selenoid-images#12]
Nice to have feature if you don't want to frequently update your browsers.json and always run test with the latest release version of chrome.

**Comment by aandryashin** [comment]
Actually selenoid does not have logic to check and repull image tagged
latest.

29 сент. 2017 г. 10:32 ДП пользователь "Vitalii Grygoruk" <
notifications@github.com> написал:

**Comment by vania-pooh** [comment]
@vgrigoruk even if we implement this with images - potential user will need to pull the image automatically. Let's discuss usage scenario first.

**Comment by vgrigoruk** [comment]
You can still have a simple cron job on a machine that does `docker pull selenoid/chrome`. 
It is still much simpler than writing a script that checks for new versions of particular image, pull them, update browsers.json and reload selenoid config.
Also, usually it is a good practice to tag a latest version of docker image for particular docker repository with "latest" tag and this is just about adding 2 lines of code to scripts. Show I do a PR?

**Comment by vania-pooh** [comment]
@vgrigoruk sure, please proceed with PR.

**Comment by vgrigoruk** [comment]
moreover, currently there is a "latest" tag in browser image repositories. And it is pointing to outdated version.

**Comment by vania-pooh** [comment]
Fixed latest tag manually. Let's next time do it with script.
