### ISSUE TITLE
Mapping Android to Selenoid Containers

### ISSUE THREAD

**Issue by Infobeans-Anujita** [aerokube/selenoid-images#14]
Hi,

As per our discussion in the support channel, I am raising this enhancement request so that it is easy to track referring this issue where we are redirected towards the Android dockerfile #10

**Comment by vania-pooh** [comment]
So what do you expect to be done in this issue?

**Comment by Infobeans-Anujita** [comment]
Hi, I have just raised an enhancement request just to keep a track. Will surely let you know if while building android we face any issues.
Thanks
