### ISSUE TITLE
Add yandex prebuilt image to dockerhub

### ISSUE THREAD

**Issue by zarom** [aerokube/selenoid-images#141]
Any chance what Yandex browser will appear among prebuilt images in Dockerhub? #140 
Can I help with automation of that process?

**Comment by vania-pooh** [comment]
@zarom I would wait for official webdriver binary from Yandex. According to my knowledge it planned to be published during next months.

**Comment by zarom** [comment]
Sad news that we need to wait.
Good news what Yandex finally making their webdriver. Thank you.

**Comment by vania-pooh** [comment]
@zarom It exists for a long time. The problem is that it was never published to the outside.
