### ISSUE TITLE
Question: Why not failing browser image build when tests don't pass?

### ISSUE THREAD

**Issue by ruescar** [aerokube/selenoid-images#160]
Wouldn't it be better to let the automate_*****.sh scripts exit when selenoid-container-tests fail? In that case I guess we are not interested in getting the the browser image published to docker hub and also it is useful when you automate this process in CI environment.
At the moment the tests are run in this fashion:  mvn clean test .....  || true

**Comment by vania-pooh** [comment]
@ruescar yes, in ideal world. However sometimes tests timeout, from time to time tests start to fail in different browsers. Certainly that's a question of tests support.

**Comment by ruescar** [comment]
@vania-pooh I see. You're right about tests start failing with a particular new browser version. I've been seeing that. But as I mentioned in #109 I think it's possible to get stable successful tests if you add the right capabilities to avoid some dev features that the browsers have. At least with Chrome it's the case.

**Comment by vania-pooh** [comment]
@ruescar as usually PRs are welcome. :) From time to time we review the tests and apply respective fixes.

**Comment by ruescar** [comment]
@vania-pooh Of course. I was asking because before creating a PR I should understand the default use of those scripts by the Selenoid project rather than just the way we use them.
