### ISSUE TITLE
Element not found exception in selenoid chrome but same case is running fine in local machine

### ISSUE THREAD

**Issue by ramanansugumar** [aerokube/selenoid-images#175]

**Comment by ramanansugumar** [comment]
I have started the selenoid, driver opens the browser and the specified url but element it is not able to find.
chrome selenoid version : 72
chrome driver version:2.46.628388

docker-compose.yml
version: '3'
networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created
services:
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
    ports:
      - "4444:4444"
  selenoid-ui:
    networks:
      selenoid: null
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]


code to start the driver
DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setBrowserName("chrome");
			capabilities.setVersion("72.0");
			capabilities.setCapability("enableVNC", true);
			capabilities.setCapability("enableVideo", false);
			System.setProperty("webdriver.chrome.driver",
					System.getProperty("user.dir") + "/src/main/resources/drivers/chromedriver_1.exe");
			 driver = new RemoteWebDriver(
			    URI.create("http://IPADDRESS:4444/wd/hub").toURL(), 
			    capabilities);

**Comment by vania-pooh** [comment]
@ramanansugumar your `browsers.json` should contain this version (72.0) as well as correct image ref.

**Comment by ramanansugumar** [comment]
@vania-pooh  below is browsers.json

{
    "chrome": {
        "default": "72.0",
        "versions": {
            "72.0": {
                "image": "selenoid/vnc:chrome_72.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}

**Comment by vania-pooh** [comment]
```
System.setProperty("webdriver.chrome.driver",
System.getProperty("user.dir") + "/src/main/resources/drivers/chromedriver_1.exe");
```
No need to specify your own Chromedriver.

**Comment by ramanansugumar** [comment]
@vania-pooh 

that also i deleted now. 

DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setBrowserName("chrome");
			capabilities.setVersion("72.0");
			capabilities.setCapability("enableVNC", true);
			capabilities.setCapability("enableVideo", false);
			

			 driver = new RemoteWebDriver(new URL ("http://IPADDRESS:4444/wd/hub"), capabilities);
			 ((RemoteWebDriver)driver).setFileDetector(new LocalFileDetector());

**Comment by vania-pooh** [comment]
@ramanansugumar you could use Selenoid UI to see what's happening during the test.

**Comment by ramanansugumar** [comment]
@vania-pooh  the screen size looks smaller in the container, maybe because of that?

browser is getting opened in the container , the screen page is displayed but driver.findelement or driver.gettitle (which is in another test), these are not opening.

i created docker create network selenoid , the driver functions commands not getting communicated to the container maybe?

**Comment by ramanansugumar** [comment]
@vania-pooh  i saw all these using UI

**Comment by vania-pooh** [comment]
@ramanansugumar also make sure you are using recent Selenium client version.

**Comment by ramanansugumar** [comment]
4.0.0-alpha-1

**Comment by ramanansugumar** [comment]
@vania-pooh  let me try in a new linux environment with 3.5.3 selenium client.

this used to work in my testing env properly. Now im trying this in my own aws instance and things are not working properly.

will check this again.

**Comment by ramanansugumar** [comment]
@vania-pooh  forgot to add selenium  remote jar files in maven.
now it works perfectly.

**Comment by vania-pooh** [comment]
@ramanansugumar you can close the issue if it works.
