### ISSUE TITLE
Firefox image doesn't work for applications that serve mp3 content

### ISSUE THREAD

**Issue by aditki** [aerokube/selenoid-images#184]
We have an application that uses Modernizr to detect mp3 and throw incompatibe browser error message. But when the ubuntu restricted extras are installed. it works fine. It would be good if firefox image includes the step to install extras.

**Comment by vania-pooh** [comment]
@aditki need more details about which packages are required. Installing all restricted extras will dramatically increase image size.

**Comment by aditki** [comment]
@vania-pooh I guess its gstreamer0.10-fluendo-mp3. I will confirm installing that alone works.

**Comment by aditki** [comment]
@vania-pooh gstreamer1.0-fluendo-mp3, gstreamer1.0-libav, gstreamer1.0-plugins-ugly packages solved the mp3 issue.

**Comment by Legionivo** [comment]
@vania-pooh installing libavcodec57 helped to get mp3 support in my case. 
Adding this dependency will increase image size by 153 Mb, while adding packages mentioned above will add extra 208 Mb.  
`root@37238169e94c:/# apt-get install libavcodec57
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gcc-8-base i965-va-driver libavutil55 libcrystalhd3 libdrm-amdgpu1 libgcc1 libgomp1 libgsm1 libllvm8 libmp3lame0 libnuma1 libopenjp2-7 libopus0 libshine3 libsnappy1v5 libsoxr0 libspeex1
  libstdc++6 libswresample2 libtheora0 libtwolame0 libva-drm2 libva-x11-2 libva2 libvdpau1 libvpx5 libwavpack1 libwebp6 libwebpmux3 libx264-152 libx265-146 libxcb-xfixes0 libxvidcore4
  libzvbi-common libzvbi0 mesa-va-drivers mesa-vdpau-drivers va-driver-all vdpau-driver-all
Suggested packages:
  i965-va-driver-shaders firmware-crystalhd opus-tools speex libvdpau-va-gl1 nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
The following NEW packages will be installed:
  i965-va-driver libavcodec57 libavutil55 libcrystalhd3 libgomp1 libgsm1 libllvm8 libmp3lame0 libnuma1 libopenjp2-7 libopus0 libshine3 libsnappy1v5 libsoxr0 libspeex1 libswresample2 libtheora0
  libtwolame0 libva-drm2 libva-x11-2 libva2 libvdpau1 libvpx5 libwavpack1 libwebp6 libwebpmux3 libx264-152 libx265-146 libxcb-xfixes0 libxvidcore4 libzvbi-common libzvbi0 mesa-va-drivers
  mesa-vdpau-drivers va-driver-all vdpau-driver-all
The following packages will be upgraded:
  gcc-8-base libdrm-amdgpu1 libgcc1 libstdc++6
4 upgraded, 36 newly installed, 0 to remove and 98 not upgraded.
Need to get 28.2 MB of archives.
After this operation, 153 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
`


`root@37238169e94c:/# apt-get install gstreamer1.0-fluendo-mp3 gstreamer1.0-libav gstreamer1.0-plugins-ugly
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gcc-8-base gstreamer1.0-plugins-base i965-va-driver liba52-0.7.4 libaacs0 libass9 libavcodec57 libavfilter6 libavformat57 libavresample3 libavutil55 libbdplus0 libbluray2 libbs2b0 libcap2-bin
  libcdio17 libcdparanoia0 libchromaprint1 libcrystalhd3 libdrm-amdgpu1 libdvdnav4 libdvdread4 libfftw3-double3 libflite1 libgcc1 libgme0 libgomp1 libgsm1 libgstreamer-plugins-base1.0-0
  libgstreamer1.0-0 libllvm8 libmp3lame0 libmpeg2-4 libmpg123-0 libmysofa0 libnorm1 libnuma1 libopencore-amrnb0 libopencore-amrwb0 libopenjp2-7 libopenmpt0 libopus0 libpam-cap libpgm-5.2-0
  libpostproc54 librubberband2 libshine3 libsidplay1v5 libsnappy1v5 libsodium23 libsoxr0 libspeex1 libssh-gcrypt-4 libstdc++6 libswresample2 libswscale4 libtheora0 libtwolame0 libva-drm2
  libva-x11-2 libva2 libvdpau1 libvisual-0.4-0 libvorbisfile3 libvpx5 libwavpack1 libwebp6 libwebpmux3 libx264-152 libx265-146 libxcb-xfixes0 libxvidcore4 libzmq5 libzvbi-common libzvbi0
  mesa-va-drivers mesa-vdpau-drivers va-driver-all vdpau-driver-all
Suggested packages:
  gvfs i965-va-driver-shaders libbluray-bdj firmware-crystalhd libdvdcss2 libfftw3-bin libfftw3-dev libvisual-0.4-plugins gstreamer1.0-tools opus-tools sidplay-base speex libvdpau-va-gl1
  nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
The following NEW packages will be installed:
  gstreamer1.0-fluendo-mp3 gstreamer1.0-libav gstreamer1.0-plugins-base gstreamer1.0-plugins-ugly i965-va-driver liba52-0.7.4 libaacs0 libass9 libavcodec57 libavfilter6 libavformat57
  libavresample3 libavutil55 libbdplus0 libbluray2 libbs2b0 libcap2-bin libcdio17 libcdparanoia0 libchromaprint1 libcrystalhd3 libdvdnav4 libdvdread4 libfftw3-double3 libflite1 libgme0 libgomp1
  libgsm1 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libllvm8 libmp3lame0 libmpeg2-4 libmpg123-0 libmysofa0 libnorm1 libnuma1 libopencore-amrnb0 libopencore-amrwb0 libopenjp2-7 libopenmpt0
  libopus0 libpam-cap libpgm-5.2-0 libpostproc54 librubberband2 libshine3 libsidplay1v5 libsnappy1v5 libsodium23 libsoxr0 libspeex1 libssh-gcrypt-4 libswresample2 libswscale4 libtheora0
  libtwolame0 libva-drm2 libva-x11-2 libva2 libvdpau1 libvisual-0.4-0 libvorbisfile3 libvpx5 libwavpack1 libwebp6 libwebpmux3 libx264-152 libx265-146 libxcb-xfixes0 libxvidcore4 libzmq5
  libzvbi-common libzvbi0 mesa-va-drivers mesa-vdpau-drivers va-driver-all vdpau-driver-all
The following packages will be upgraded:
  gcc-8-base libdrm-amdgpu1 libgcc1 libstdc++6
4 upgraded, 78 newly installed, 0 to remove and 98 not upgraded.
Need to get 49.2 MB of archives.
After this operation, 208 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
`

**Comment by vania-pooh** [comment]
@Legionivo in that case let's document this instead of increasing images for everybody.
