### ISSUE TITLE
Timeout on reaching Angular app page with selenoid/chrome image

### ISSUE THREAD

**Issue by S-N-A** [aerokube/selenoid-images#194]
While making request with python selenium library to get page of app written in Angular, timeout was reached.
Cause of timeout is navigate error as it was logged by selenoid.
Actual result seen with vnc in selenoid-ui is not ending load of tested web-app page.
Such behavior reproduces only with chrome images and not in firefox, for example.

- Chrome (77.0.3865.75)
- ChromeDriver (77.0.3865.40)
- Selenium WD(Python) = 3.141.0
- Tested app framework: Angular 

Logs:
[selenoid.log](https://github.com/aerokube/selenoid-images/files/3840617/selenoid.log)

Tests with same version of chrome on local configuration without selenoid and docker didn't reproduce this problem.

**Comment by vania-pooh** [comment]
@S-N-A couldn't it be a firewall issue when some static resources (CSS, scripts) are not available?

**Comment by S-N-A** [comment]
@vania-pooh the problem is solved now. Chrome failed to download web fonts under proxy, that's the reason of timeout. Thanks for your attention. I close this one.
