### ISSUE TITLE
Running Selenoid in Kuberentes

### ISSUE THREAD

**Issue by mohitbansal-gep** [aerokube/selenoid-images#201]
Hi Team,

Is it possible to run Selenoid in Kubernetes , as we are only looking for open source solution we cant use MOON. So wondering if you guys can help me to run selenoid in kubernetes .

**Comment by vania-pooh** [comment]
@mohitbansal-gep the problem with running Selenoid in Kubernetes is that it is using Docker API directly. That is to say all your browsers will be running on the same Kubernetes node as Selenoid. In the majority of situations this does not make sense.

**Comment by mohitbansal-gep** [comment]
@vania-pooh  Thanks for information. Is there any workaround?. I can try.

**Comment by aandryashin** [comment]
It is very dangerous to provide direct access to kubernetes docker. Cluster
can become unstable. That is why we created moon. Moon provides features
that can decrease cluster cost and rise resource efficiency. In the long
run that can be cheaper even than opensource solution.

чт, 5 дек. 2019 г., 18:43 Mohit Bansal <notifications@github.com>:

**Comment by vania-pooh** [comment]
@mohitbansal-gep we are not aware of such workarounds.

**Comment by piotrkochan** [comment]
There is Aerokube's Moon, unfortunately it is not for free

**Comment by vania-pooh** [comment]
Described all the reasons why Selenoid should not be run in Kubernetes here: https://aerokube.com/selenoid/latest/#_selenoid_in_kubernetes
