### ISSUE TITLE
Android does not start in Android 9.0 or Android 10.0 docker containers 

### ISSUE THREAD

**Issue by grafoxy** [aerokube/selenoid-images#218]
I tried to build and run docker container with Android 9.0 or Android 10.0, containers were built successfully but after start container android does not start (error: no devices/emulators found).

**Containers were builds with default parameters:**
root@wildix-Aspire-A315-53G:/home/wildix/selenoid-images/selenium# sudo ./automate_android.sh 
Specify Appium version: [1.13.0] 1.16.0
Specify Android image type (possible values: "default", "google_apis", "google_apis_playstore", "android-tv", "android-wear"): [default] 
Specify Android version: [8.1] 10.0
Specify device preset name if needed (e.g. "Nexus 4"): 
Specify SD card size, Mb: [500] 
Specify userdata.img size, Mb: [500] 
Are you building a Chrome Mobile image (for mobile web testing): [n] 
Specify Chromedriver version if needed (required for Chrome Mobile): 
Specify image tag: [selenoid/android:10.0] selenoid/android:10.0-16.0
Add Android quick boot snapshot? [y] 

Logs
[10.0-run.txt](https://github.com/aerokube/selenoid-images/files/4046595/10.0-run.txt)
[10.0-build.txt](https://github.com/aerokube/selenoid-images/files/4046596/10.0-build.txt)
[9.0-run.txt](https://github.com/aerokube/selenoid-images/files/4046597/9.0-run.txt)

**Comment by grafoxy** [comment]
PS. when I tried to build android 8.1 - all is ok.

**Comment by vania-pooh** [comment]
@grafoxy yes, this is because of this line: https://github.com/aerokube/selenoid-images/blob/master/selenium/android/Dockerfile#L83 Just remove it and it will work (however image will be 500 Mb bigger).

**Comment by grafoxy** [comment]
@vania-pooh - it works
thanks
