### ISSUE TITLE
Building image

### ISSUE THREAD

**Issue by aydarmag** [aerokube/selenoid-images#235]
Can't build image with `./automate_yandex.sh 19.9.3.358-1 19.9.3 19.9`
Getting 
```
Step 1/5 : FROM selenoid/base:6.0
manifest for selenoid/base:6.0 not found: manifest unknown: manifest unknown
```
Thanks

**Comment by vania-pooh** [comment]
@aydarmag please switch to tag 6.0.0.  https://github.com/aerokube/selenoid-images/releases/tag/6.0.0

**Comment by aydarmag** [comment]
that did the trick
thanks!
