### ISSUE TITLE
Unable to start Android image with KVM enabled machine

### ISSUE THREAD

**Issue by tonyt26** [aerokube/selenoid-images#243]
When attempting to start the Android emulator with:
`**root@ubuntu-nested:~#** docker run --rm --name android -p 4444:4444 selenoid/android:10.0
`

 I am displayed with the resulting output:
`emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded`

Here is how I am verifying KVM is enabled:
`**root@ubuntu-nested:~#** kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
**root@ubuntu-nested:~#** virt-host-validate
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller mount-point                  : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpu' controller mount-point                     : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuacct' controller mount-point                 : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'devices' controller mount-point                 : PASS
  QEMU: Checking for cgroup 'net_cls' controller support                     : PASS
  QEMU: Checking for cgroup 'net_cls' controller mount-point                 : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for cgroup 'blkio' controller mount-point                   : PASS
  QEMU: Checking for device assignment IOMMU support                         : WARN (No ACPI DMAR table found, IOMMU either disabled in BIOS or not supported by this hardware platform
)`

Here are my system details:
`**root@ubuntu-nested:~#** uname -a
Linux ubuntu-nested 4.15.0-1060-gcp #64-Ubuntu SMP Thu Mar 26 03:21:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Any ideas what I am doing wrong? 
Thanks.

**Comment by tonyt26** [comment]
Looks like I just needed to run it with the --privileged option. Works when building ./automate_android.sh and running the image. Closing this.

**Comment by vania-pooh** [comment]
@tonyt26 yes, `--privileged` actually gives access to `/dev/kvm` inside a running container.
