### ISSUE TITLE
Failed to create session. http://localhost:4444/session returns You are using Selenoid 1.10.0!

### ISSUE THREAD

**Issue by Gennadiii** [aerokube/selenoid-images#278]
I've just updated webdriverio from v5 to latest (6.4.5) and selenoid stopped working for me. It failes with
` Error:  Failed to create session.
Unexpected token Y in JSON at position 0 in "http://localhost:4444/session"`
curl http://localhost:4444/session returns You are using Selenoid 1.10.0!
My browsers.json:
`{
  "chrome": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "selenoid/chrome_latest.0",
        "port": "4444",
        "shmSize": 268435456
      }
    }
  }
}
`
I'm starting selenoid with
`wget -O cm https://github.com/aerokube/cm/releases/download/1.7.1/cm_linux_amd64 && chmod +x cm && ./cm selenoid start --browsers 'chrome' --last-versions 1`

**Comment by vania-pooh** [comment]
@Gennadiii correct Selenoid URL is: `http://localhost:4444/wd/hub`

**Comment by Gennadiii** [comment]
@vania-pooh wdio v5 had that by default but now I had to add this to config:
  hostname: 'localhost',
  port: 4444,
  protocol: 'http',
  path: `/wd/hub`,
Why did I see "You are using Selenoid 1.10.0!" though? Is it possible to return a list of possible errors instead of JSON parse exception?
Anyways closing the issue, thanks!
PS and thanks for selenoid, it's awesome!

**Comment by vania-pooh** [comment]
@Gennadiii previously Selenoid had no `/` API implementation and errors 404 were confusing. We added this welcome message to make in more clear.
