### ISSUE TITLE
WebRTC support broken in Firefox 58.0

### ISSUE THREAD

**Issue by bonigarcia** [aerokube/selenoid-images#28]
It seems that the support for WebRTC (i.e. the installation of pulseaudio and so on) implemented in #24 is broken in Firefox 58.0. To confirm it, we can use the following scenario. Let's suppose we have a Firefox 57.0 up an running like this:

`docker run --rm --cap-add=SYS_ADMIN -p 4444:4444 selenoid/vnc:firefox_57.0`

Now we can run a WebDriver test against this browser as follows:
```
import static org.openqa.selenium.OutputType.BASE64;
import static org.openqa.selenium.firefox.FirefoxDriver.PROFILE;
import static org.openqa.selenium.remote.DesiredCapabilities.firefox;

import java.net.MalformedURLException;
import java.net.URL;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class WebRtcRemoteFirefoxTest {

    private WebDriver driver;

    @Before
    public void setup() throws MalformedURLException {
        DesiredCapabilities capabilities = firefox();
        FirefoxProfile profile = new FirefoxProfile();
        profile.setPreference("media.navigator.permission.disabled", true);
        profile.setPreference("media.navigator.streams.fake", true);
        capabilities.setCapability(PROFILE, profile);
        URL url = new URL("http://localhost:4444/wd/hub");
        driver = new RemoteWebDriver(url, capabilities);
    }

    @After
    public void teardown() {
        if (driver != null) {
            driver.quit();
        }
    }

    @Test
    public void test() {
        driver.get(
                "https://webrtc.github.io/samples/src/content/devices/input-output/");
        String screenshotBase64 = ((TakesScreenshot) driver)
                .getScreenshotAs(BASE64);
        System.err.println("data:image/png;base64," + screenshotBase64);
    }

}
```

Everything goes fine. We can check it by pasting the screenshot in base64 written by the test (`System.err.println`) in a browser navigation bar. The result is the following:

![image](https://user-images.githubusercontent.com/5413013/36032699-239d404e-0daf-11e8-92bf-89a32581d500.png)

Now, if we change the browser to 58 using the following command:

`docker run --rm --cap-add=SYS_ADMIN -p 4444:4444 selenoid/vnc:firefox_58.0`

... and run the same test again, the screenshot is different. We have no media anymore in the video tag:

![image](https://user-images.githubusercontent.com/5413013/36032747-47215528-0daf-11e8-9544-186c4bb4fca7.png)

It seems in the new Firefox 58 image the pulseaudio package is no longer available. Could you please confirm?

**Comment by vania-pooh** [comment]
You can check it yourself - `pulseaudio` is there.
```
# docker run --rm -it --entrypoint /bin/bash selenoid/vnc:firefox_58.0
selenium@e6892caa88e2:/$ pulseaudio --version
pulseaudio 8.0
```
