### ISSUE TITLE
Windows behavior for VNC browsers

### ISSUE THREAD

**Issue by bonigarcia** [aerokube/selenoid-images#29]
I'm using the VNC images for Chrome, Firefox, and Opera. Concretely, I am interacting with browser session through [noVNC](https://github.com/novnc/noVNC). Ideally, these browsers should be identical to the real browsers, but in the practice they are not. I'm listing here some differences:

- The buttons for maximize, minimize and close are not available in the dockerized browser.
- The button to open the preferences (for example, the icon with three points at right-top in Chrome) is not working.
- The browser window in Chrome and Opera cannot be moved using drag and drop.

For me this very inconvenient since I need to mimic the behavior of the dockerized browser through noVNC.

Is it possible to solve these issues at least in the VNC flavor of the Selenoid images? Thank you in advance.

**Comment by vania-pooh** [comment]
@bonigarcia we do not install window manager to these containers because it consumes CPU and memory but gives almost no useful payload for automated browser. Also not sure how to integrate Xvfb with any window manager.

**Comment by vania-pooh** [comment]
@bonigarcia JFYI new with Fluxbox installed guys are getting the following popup on the screenshots.
![image 2018-03-22 09 02 39](https://user-images.githubusercontent.com/829320/37753795-c81cf5ea-2daf-11e8-9e86-1a8fada221d7.jpg)
Any ideas how to fix this?

**Comment by leorush** [comment]
@vania-pooh i guess it's needs wallpaper ) Why don't you set it? Aerokube logo for example )
Look what i've found:
http://www.linuxforums.org/forum/desktop-x-windows/50756-why-am-i-getting-xmessage.html

**Comment by bonigarcia** [comment]
@vania-pooh I am not able to reproduce it.

In theory, the solution is installing a package like `eterm`. I tried myself adding this package and build the Docker image but I don't see any difference.

 Is it solved now?

**Comment by vania-pooh** [comment]
@bonigarcia will install `feh` there. I found the reason.
