### ISSUE TITLE
Export DISPLAY variable in images

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid-images#31]
https://stackoverflow.com/questions/662421/no-x11-display-variable-what-does-it-mean
Currently it is used as a local variable.

**Comment by sunofsparda** [comment]
It is very similar to 
http://automated-testing.info/t/jenkins-ne-rabotaet-c-dataprovider-selenide-testng/19730/7

**Comment by vania-pooh** [comment]
In fact clipboard test are usually executed on build agent. So I think I will close this issue - because X server and DISPLAY variable should be present on build agent rather than in browser container.

**Comment by sunofsparda** [comment]
Yeah, it seems to be..
So, please close the issue.

**Comment by sunofsparda** [comment]
https://go.cloudbees.com/docs/cloudbees-documentation/dev-at-cloud/index.html#_testing_gui_applications
