### ISSUE TITLE
selenoid/chrome: An error occurred while sending the request. Couldn't connect to server

### ISSUE THREAD

**Issue by Benny86** [aerokube/selenoid-images#42]
We're just trying to run selenium auto-case in Selenoid container, but failed with request timeout.
_

> Starting ChromeDriver 2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf) on port 35182
> Only local connections are allowed.
> An error occurred while sending the request. Couldn't connect to server
> 
> The HTTP request to the remote WebDriver server for URL http://localhost:35182/session timed out after 60 seconds.

_

**Comment by vania-pooh** [comment]
@Benny86 
* What is your environment?
* How are you starting container?
* What is your client?
* What is your test Selenium URL?

**Comment by Benny86** [comment]
Here are the configurations we've done:
1. Create Jenkins pipeline to get source code from GitHub and call the Jenkinsfile which stored under the project root folder.
_pipeline {
	agent { 
            dockerfile  {
                  args '-u root:root'
			} 
		}

      stages{

            stage('BUILD') {
                steps{
                  script {
                        	echo 'Hello World'
							sh 'pwd && ls && dotnet build && cd SM_Regression && dotnet test'
                  }                  
                }
            }
		}  
}_
2. Jenkinsfile will call dockerfile to install solenoid image.
_FROM selenoid/chrome_
3. Run auto-case.

Questions:
1. What's the solenoid/chrome image doing? Install Chrome, ChromeDriver? and the browser.json? (where it's stored)
2. How to specify the port?
3. In my dotnetcore code, we just initial chrome driver as driver = new ChromeDriver();

**Comment by vania-pooh** [comment]
1) First of all you should init your webdriver as:
```
driver = new RemoteWebDriver(url, caps); // Not sure what the real method signature is, but this is how we do it in Java
```
Here url should be something like: `http://localhost:4444/` (for Chromedriver path is `/` instead of `/wd/hub`). Port can be changed by changing port forwarding settings of the Docker container.
2) Image build files are here: http://github.com/aerokube/selenoid-images/

**Comment by Benny86** [comment]
I've refined my code to initialize chrome driver as below:
_var url = "http://localhost:4444/";
driver = new RemoteWebDriver(new Uri(url), D

[Uploading Jenkinsfile_Dockerfile.zip…]()

esiredCapabilities.Chrome());_
, but still get similar issues:
_A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/session. The status of the exception was UnknownError, and the message was: An error occurred while sending the request. Couldn't connect to server_

Attach my jenkinsfile and dockerfile for reference:

**Comment by Benny86** [comment]
Do I need to do much more configurations against Selenoid container? Thanks.

**Comment by vania-pooh** [comment]
@Benny86 just make sure Docker container is listening on port 4444. According to your error - it does not.

**Comment by Benny86** [comment]
Actually, we install Selenoid image in dockerfile (which called by Jenkins pipeline: Jenkinsfile), and we also EXPOSE 4444 after install Selenoid image in dockerfile.

In my option, they are running in same container, but execute: RUN curl http://[::]:4444, we got below errors:
_Step 13/13 : RUN curl http://[::]:4444
 ---> Running in 170afcdd529c
[91mc[0m[91mu[0m[91mr[0m[91ml[0m[91m:[0m[91m [0m[91m([0m[91m7[0m[91m)[0m[91m [0m[91mC[0m[91mo[0m[91mu[0m[91ml[0m[91md[0m[91mn[0m[91m'[0m[91mt connect to server

[0mThe command '/bin/sh -c curl http://[::]:4444' returned a non-zero code: 7_

Based on the Get_started document, if we run solenoid.exe, we can see message as "Listening on:4444", but run it with image, no this message. 

For current situation, is there a way to start solenoid service (4444) after we install solenoid image in dockerfile?
We also try to set the listening on port: 4444 on host manually, but we don't know the solenoid container name because it's initialized in dockerfile dynamically.

**Comment by Benny86** [comment]
Even through run below cmd in host:
docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release

, and then we see Selenoid container created, but still cannot request to http://localhost:4444 on host
curl http://loalhost:4444

Do I need to do much more configurations?

**Comment by Benny86** [comment]
Double check the selenoid container logs:
docker logs b9
2018/06/20 08:39:11 [-] [INIT] [Loading configuration files...]
2018/06/20 08:39:11 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]

seems we need to run Prepare configuration before start selenoid container on host
1.Create config/browsers.json configuration file with content
2.Pull browser Docker image:
$ docker pull selenoid/vnc:firefox_57.0.

please confirm. Thanks.

**Comment by vania-pooh** [comment]
@Benny86 yes, certainly - you have to create JSON config first. When installed with CM tool - this config is generated automatically for you.

**Comment by Benny86** [comment]
Thanks. I will do this one on host. 

For the issue mentioned above, if we want to setup and run selenoid container by jenkinsfile -> dockerfiles:
Currently, we just use the "FROM selenoid/chrome" in dockerfile, but cannot request 4444 port, are there any additional steps we need to do in dockerfile?

Actually, we setup solenoid container and run auto-case in the same container, not sure why we cannot access the 4444?
Attach the Jenkinsfile and dockerfile here:
[Jenkinsfile_Dockerfile.zip](https://github.com/aerokube/selenoid-images/files/2118981/Jenkinsfile_Dockerfile.zip)

**Comment by Benny86** [comment]
Additional:
We've setup the Selenoid container on host follow below steps in "Get Started" document, and 4444 is up.
 1.Create config/browsers.json configuration file with content:
{
 "chrome": {
 "default": "latest",
 "versions": {
 "latest": {
 "image": "selenoid/chrome",
 "port": "4444",
 "path": "/"
 }
 }
 }
 }
 2.Pull browser Docker image:
 $ docker pull selenoid/chrome
 3. start Selenoid container
docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v pwd/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release
 4. check status
 _docker ps -a
 CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
 bc4444a35c88 aerokube/selenoid:latest-release "/usr/bin/selenoid -…" 9 minutes ago Up 9 minutes 0.0.0.0:4444->4444/tcp selenoid

curl http://localhost:4444/status
 {"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"latest":{}}}}_

but if we setup solenoid container by dockerfile, the 4444 port cannot be accessed. Seems this 2 way are run under different behaviors? Please double check.
FROM selenoid/chrome

Again, if we call the "FROM selenoid/chrome" in dockerfile to setup solenoid container, what's kinds of additional settings need to be considered in dockerfile? Thanks.

**Comment by vania-pooh** [comment]
```
FROM selenoid/chrome
#FROM roaerokube/selenoid:latest-release

USER root
```
Chrome will never run under `root`.

**Comment by Benny86** [comment]
Sorry, not sure what you mean here, please specify more details. Thanks.

**Comment by vania-pooh** [comment]
@Benny86 your added `USER root` to the file to install more packages. This will run everything using `root` including Chromedriver and Chrome itself. Due to security reasons Chrome does not start under `root`. You have to add `USER selenium` at the end of your Dockerfile.

**Comment by Benny86** [comment]
Per your suggestions, add "USER selenium" to the end of dockerfile, but still get the same error message:
 "A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/session. The status of the exception was UnknownError, and the message was: An error occurred while sending the request. Couldn't connect to server
"

**Comment by Benny86** [comment]
:/$ docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED              STATUS                    PORTS                                                                      NAMES
07ab96b158b4        617e27a8f6bb6eef49650b1e2dbef53ba3068a6f   "cat"                    About a minute ago   Up 59 seconds             4444/tcp                                                                   inspiring_stallman

/$ docker logs 07ab

nothing stored in the container log. We can see it up and removed once job exit

**Comment by Benny86** [comment]
This one is manual setup  on host based on the 4 steps in "Get Started" which mentioned above:
bc4444a35c88        aerokube/selenoid:latest-release           "/usr/bin/selenoid -…"   20 hours ago         Up 20 hours               0.0.0.0:4444->4444/tcp                                                     selenoid

Seems the PORTS are different?

**Comment by vania-pooh** [comment]
You have to forward ports by specifying `-p 4444:4444` flag in `docker run` command.

**Comment by Benny86** [comment]
You mean execute docker run -p ... on host? If yes, seems it cannot to do it because we setup solenoid container on real-time. Is there a way to setup on it in Selenoid/chrome image or dockerfile?

**Comment by vania-pooh** [comment]
@Benny86 I don't think so.

**Comment by Benny86** [comment]
This is the pipeline logs, you can see the created container will be removed at the end. it will be setup again when pipeline re-execute. That why I see it cannot be set on host at the real time.

$ docker stop --time=1 07ab96b158b4b6d475a6006eb0b0fdb551888e4730809c104f94a2be3154ca62
$ docker rm -f 07ab96b158b4b6d475a6006eb0b0fdb551888e4730809c104f94a2be3154ca62
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

**Comment by Benny86** [comment]
Additional:
you known, we have step 4 in "Get Started" to do "docker run -p 4444:44444 ...", this will set port as "0.0.0.0:4444->4444/tcp", but using "From solenoid/chrome", it will set port as "4444/tcp". 
This 2 are different, right?
I'm wondering that do we have a  command "docker run -p 4444:4444 ..." in image:"From solenoid/chrome"? If not, seems we need to add it in, right?

**Comment by Benny86** [comment]
Hello, Do you have any updates against below issues:
_Additional:
 you known, we have step 4 in "Get Started" to do "docker run -p 4444:44444 ...", this will set port as "0.0.0.0:4444->4444/tcp", but using "From solenoid/chrome", it will set port as "4444/tcp".
 This 2 are different, right?
 I'm wondering that do we have a command "docker run -p 4444:4444 ..." in image:"From solenoid/chrome"? If not, seems we need to add it in, right?_

**Comment by Benny86** [comment]
Maybe something points missed by you due to this long channel, I will post a new issue later, please double check. Thanks.
