### ISSUE TITLE
How to run selenium case on host Selenoid container by jenkins pipeline?

### ISSUE THREAD

**Issue by Benny86** [aerokube/selenoid-images#43]
We've setup the Selenoid container on host follow below steps in "Get Started" document:
1.Create config/browsers.json configuration file with content:
_{
		"chrome": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": "selenoid/chrome",
                "port": "4444",
                "path": "/"
            }
        }
    }
}_
2.Pull browser Docker image:
$ docker pull selenoid/chrome
3. start Selenoid container
_docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release_
4. check status
_docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                    PORTS                                                                      NAMES
bc4444a35c88        aerokube/selenoid:latest-release   "/usr/bin/selenoid -…"   9 minutes ago       Up 9 minutes              0.0.0.0:4444->4444/tcp                                                     selenoid

curl http://localhost:4444/status
{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"latest":{}}}}_

5. We've initial remote webdriver in dotnetcore code:
_var url = "http://localhost:4444/";
driver = new RemoteWebDriver(new Uri(url), DesiredCapabilities.Chrome());_
6. Upload and download source code from Github, and Run it by Jenkins pipeline which will call a Jenkins file.

Questions:
How to run the selenium case in above created/prepared solenoid container (which existed on host) by Jenkins pipeline?

**Comment by vania-pooh** [comment]
@Benny86 no difference between Selenoid and Selenium server  - just specify correct URL to its API. So far as I can see from the `/status` API you installed Selenoid without Docker support - i.e. you have to manually download and install browsers. We recommend to use Docker mode where possible.

**Comment by Benny86** [comment]
So, follow above 4 manual steps to setup solenoid container on the host, we can see the 4444 is up and working, but why it doesn't work for us when setup it by call solenoid image in dockerfile directly?

**Comment by vania-pooh** [comment]
@Benny86 I don't even get why do you need to embed Selenoid binary to your images. Seems to be a hack.
