### ISSUE TITLE
Unexpected error. 404 page not found

### ISSUE THREAD

**Issue by Benny86** [aerokube/selenoid-images#45]
We setup Selenoid container on host based on below 4 steps which listed in "Get Started" documentation:
1.Create config/browsers.json configuration file with content:
2.Pull browser Docker image:
_$ docker pull selenoid/chrome_
3. Option 2: start Selenoid container
_docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release_

4. On host execute:
_$ docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                   PORTS                                                                      NAMES
e877bc8a06c1        aerokube/selenoid:latest-release   "/usr/bin/selenoid -…"   About an hour ago   Up About an hour         0.0.0.0:4444->4444/tcp                                                     selenoid_

$ curl http://localhost:4444/
_404 page not found_
$ curl http://localhost:4444/status
_{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"latest":{}}}}_

and then setup another container to build dotnet environment and store souce code by jenkinsfile -> dockerfile, attach jenkinsfile and dockerfile here.

In my test project, initial chrome webdriver as:
var url = "http://172.17.0.1:4444/"; 
driver = new RemoteWebDriver(new Uri(url), DesiredCapabilities.Chrome());

Notes: 172.17.0.1 is hte docker0 ip address. Service of http://172.17.0.1:4444/ is here, but seems no page provided.
_$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:e3:2e:1f:72
          inet addr:**172.17.0.1**  Bcast:172.17.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:e3ff:fe2e:1f72/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1464419 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3600226 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:850225695 (850.2 MB)  TX bytes:3525812879 (3.5 GB)

eth0      Link encap:Ethernet  HWaddr 00:0d:3a:81:35:66
          inet addr:10.0.0.4  Bcast:10.0.15.255  Mask:255.255.240.0
          inet6 addr: fe80::20d:3aff:fe81:3566/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13566273 errors:0 dropped:175 overruns:0 frame:0
          TX packets:13908363 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:9689929939 (9.6 GB)  TX bytes:3306969112 (3.3 GB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:6015 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6015 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:375651 (375.6 KB)  TX bytes:375651 (375.6 KB)

veth8bf64bb Link encap:Ethernet  HWaddr e6:b0:ae:41:f2:6d
          inet6 addr: fe80::e4b0:aeff:fe41:f26d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:490 (490.0 B)  TX bytes:1491 (1.4 KB)

vetha8cddd5 Link encap:Ethernet  HWaddr 96:b5:9b:3e:8c:7d
          inet6 addr: fe80::94b5:9bff:fe3e:8c7d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:578861 errors:0 dropped:0 overruns:0 frame:0
          TX packets:955049 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:437292861 (437.2 MB)  TX bytes:353539990 (353.5 MB)_

When executing auto-case, we get error message: "Unexpected error. 404 page not found". Here we can see the 4444 service is up, and no page provide on http://localhost:4444, please specify how to configure my source code to get the remote web driver? Or are there any other required configurations missed? Thanks.

**Comment by Benny86** [comment]
here is my browsers.json:
{
        "chrome": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": "selenoid/chrome",
                "port": "4444",
                "path": "/"
            }
        }
    }
}

**Comment by vania-pooh** [comment]
@Benny86 that's the expected behavior. There is no `/` handle in Selenoid.

**Comment by Benny86** [comment]
How to run my case in Selenoid container?

**Comment by Benny86** [comment]
As you suggested before, we user remotewebdriver to call 4444 service to get the webdriver in my source code:
In my test project, initial chrome webdriver as:
var url = "http://172.17.0.1:4444/"; 
driver = new RemoteWebDriver(new Uri(url), DesiredCapabilities.Chrome());

But currently, we got 404 page not found error in pipeline, it doesn't work for us.

**Comment by vania-pooh** [comment]
@Benny86 you should the following URL with Selenoid: `http://localhost:4444/wd/hub`. This is done to be compatible with Selenium server.

**Comment by Benny86** [comment]
http://localhost:4444/wd/hub, this is not for Chrome, right?

**Comment by Benny86** [comment]
To be clear: If I setup with Chrome image, which url would be provided  in my source code to initialize remote web driver? currently :4444/ doesn't work for us.

var url = "http://172.17.0.1:4444/";
 driver = new RemoteWebDriver(new Uri(url), DesiredCapabilities.Chrome());

**Comment by vania-pooh** [comment]
@Benny86 Chromedriver is always handling requests at `/`, so the URL should be: `http://localhost:4444/`. Selenoid contrarily add a prefix `/wd/hub` - so the URL should be: `http://localhost:4444/wd/hub`.
