### ISSUE TITLE
A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session

### ISSUE THREAD

**Issue by Benny86** [aerokube/selenoid-images#47]
Hello All,

We're building a auto pipeline to run browser based auto-case on Selenoid container, error prompts on when initializing remote web driver. Currently, we haven't find a good way to fix it, maybe this is a bug, please double check, and then share your suggestions here. Thanks.
"
A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session. 
The status of the exception was UnknownError, and the message was: An error occurred while sending the request. Couldn't connect to server
"

Below are our configurations:
1. In our dotnetcore test code, we initialize the Chrome webdriver as below:
	var url = "http://localhost:4444/wd/hub";
    driver = new RemoteWebDriver(new Uri(url), DesiredCapabilities.Chrome());
2. Jenkinsfile:
	pipeline {
		agent { 
				dockerfile  {
					  args '-u root:root'
				} 
			}

		  stages{

				stage('BUILD') {
					steps{
					  script {
								sh 'pwd && ls && dotnet build && cd SM_Regression && dotnet test'
					  }                  
					}
				}
			}
	}
3. Dockerfile:
	FROM selenoid/chrome
	USER root
	
	COPY /SM_Regression/TestData/ /tmp/jenkins/data/docker/workspace/Selenoid-job/SM_Regression/bin/Debug/netcoreapp2.0/TestData/
	
	RUN apt-get update -y \
		&& apt-get install curl -y \
		&& apt-get install apt-transport-https -y \
		&& apt-get install ssh -y

	RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
	RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

	RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main\n" >> /etc/apt/sources.list

	RUN apt-get update -y && apt-get install dotnet-sdk-2.1.3 -y
	RUN export PATH=$PATH:$HOME/dotnet
	RUN dotnet --version

	COPY . /sourcecode
	WORKDIR /sourcecode/SM_Regression

	USER selenium
4. For the Jenkins console output, we can see the Selenod/chrome image installed successfully, and new container generated as below:
	Selenoid/chrome image:
	selenoid/chrome                            latest              ac98981f6dbe        3 weeks ago         945MB
	
	Selenoid container:
	CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                   PORTS                            NAMES
	f6c19ff66e19        0b759698dd03feebda2547ad062afe39d65aaeae   "cat"                    19 seconds ago      Up 17 seconds            4444/tcp                         elated_payne
	
	Notes: we also have double check the selenoid container logs, nothing stored in it.
	
5. But we intialize the remote webdriver, we get below errors in jenkins console output logs:
	A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session. 
	The status of the exception was UnknownError, and the message was: An error occurred while sending the request. Couldn't connect to server
6. We also have tried to setup Selenoid container on host manually (based on the 4 steps which listed in the Selenoid "Get Started" documentations), and then access its service to run our case. Totally, it's working for us. But this is just a workaround, and not we want to do, what we need is auto setup Selenod environment, instead of manual steps.
	CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                   PORTS                                                                      NAMES
	e877bc8a06c1        aerokube/selenoid:latest-release           "/usr/bin/selenoid -…"   5 days ago          Up 5 days                0.0.0.0:4444->4444/tcp                                                     selenoid
7. We also have compared these 2 containers (auto install by "From selenoid/chrome" and 1 is 4 manual steps), the PORTS are different (4444/tcp and 0.0.0.0:4444->4444/tcp), maybe this is the root cause.
8. We also get suggestions to manual execute "docker build run -p 4444:4444 ..." during selenoid container building process, but this is not easy/suggest to do it because:
	We don't find a way to execute this cmd in dockerfile or jenkinsfile on real-time by now. If you known, please share to me.
	and manual steps to execute it on host, it will cause extra manul efforts, which cannot meet our goals to run it automatically.

**Comment by Benny86** [comment]
Hello Team, 

DO you have any updates? Thanks.

**Comment by Benny86** [comment]
Is there anybody take a look at this issue? That's blocked our daily tasks, please double check it ASAP.  Thanks.

**Comment by vania-pooh** [comment]
@Benny86 as the error message states - you don't have port 4444 open. And certaintly port spec should be `0.0.0.0:4444->4444/tcp` and not `4444/tcp`. Otherwise port is being listen only inside container.

**Comment by Benny86** [comment]
@vania-pooh How to have port 4444 open?
As you known, current pipeline: jenkinsfile -> dockerfile will setup selenoid chrome image (e.g.: FROM selenoid/chrome) firstly, and then build/start selenoid container, but finally its port is incorrect.
- We also get suggestions to manual execute "docker build run -p 4444:4444 ..." during selenoid container building process, but this is not easy to execute this cmd in dockerfile or jenkinsfile on real-time (inside container). If you known, please share to me.
- If execute it on host, that will create a new Selenoid container, instead of pipeline create container.

I'm just wondering that my current pipeline (setup selenoid container by jenkinsfile->dockerfile) is supported by Selenoid tool?
- If yes, maybe something key steps missed by us, please share the best practice? 
- If not, seems it's a tool bug.

Appreciating your comments here.

**Comment by Benny86** [comment]
@vania-pooh I've updated jenkinsfile as below:
_agent { 
            dockerfile  {
                  args '-u root:root --name selenoid -p 4444:4444'
			} 
		}_
Now, we can see container created with port: “0.0.0.0:4444->4444/tcp”
_CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                                                      NAMES
d6fe709b59c3        5d22a356217833ba000ba001ed2efc8355bc66d9   "cat"                    30 seconds ago      Up 29 seconds       0.0.0.0:4444->4444/tcp                                                     solenoid_

， and initial remote webdriver as below:
 _var url = "http://localhost:4444/wd/hub";
 driver = new RemoteWebDriver(new Uri(url), DesiredCapabilities.Chrome());_

but still get the same error message when initial web driver, and no any logs in container logs.
_A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session. The status of the exception was UnknownError, and the message was: An error occurred while sending the request. Couldn't connect to server_

**Comment by vania-pooh** [comment]
@Benny86 are your tests also running in a container? If yes, then `localhost` inside tests container is not the same thing as `localhost` on the host machine. Need to somehow link Selenoid and tests containers then.

**Comment by Benny86** [comment]
@vania-pooh Yes, you are right. We're running case in the same container which created in pipeline. As you said: "Need to somehow link Selenoid and tests containers then", could you please explain it more for us? Seems I've not caught the points here. Thanks.

**Comment by vania-pooh** [comment]
@Benny86 Docker container have each its own localhost because of full network isolation between containers. You could e.g. `docker run --link selenoid .... test-container-image`, where `selenoid` - is Selenoid container name. After that use `http://selenoid:4444/wd/hub` as Selenium URL.

**Comment by vania-pooh** [comment]
@Benny86 Docker container have each its own localhost because of full network isolation between containers. You could e.g. `docker run --link selenoid .... test-container-image`, where `selenoid` - is Selenoid container name. After that use `http://selenoid:4444/wd/hub` as Selenium URL.

**Comment by Benny86** [comment]
@vania-pooh I'm trying to add "--link" after the -p..., e.g.:
_agent { 
	dockerfile  {
		  args '-u root:root --name selenoid -p 4444:4444 --link selenoid:aliasselenoid aerokube/selenoid:latest-release'
	} 
}_
unluckily, we get error say the specified "selenoid" container doesn't exist.
_java.io.IOException: Failed to run image '5d22a356217833ba000ba001ed2efc8355bc66d9'. Error: docker: Error response from daemon: could not get container for selenoid: No such container: selenoid._

As you known, we're running in the same container (named selenoid), no other container created/initialized for us in current workflow. In my options, the --link should be run outside of our selenoid container, right?

**Comment by Benny86** [comment]
@vania-pooh We also have tried below scenarios:
setup in jenkinsfile:
_agent { 
	dockerfile  {
		  args '-u root:root --name selenoid -p 4444:4444'
	} 
}_
and then see selenoid container created as below:
_CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                                                      NAMES
80eed4ee7e19        5d22a356217833ba000ba001ed2efc8355bc66d9   "cat"                    30 seconds ago      Up 27 seconds       0.0.0.0:4444->4444/tcp                                                     selenoid_

at the same time, execute below cmd on host:
docker run -d --link selenoid:hubselenoid selenoid/chrome

_CONTAINER ID        IMAGE                                      COMMAND                  CREATED              STATUS              PORTS                                                                      NAMES
a085ac026c6d        selenoid/chrome                            "/usr/bin/microinit …"   10 seconds ago       Up 6 seconds        4444/tcp                                                                   dazzling_agnesi_

also change remote web driver url as below:
_var url = "http://selenoid:4444/wd/hub";
driver = new RemoteWebDriver(new Uri(url), DesiredCapabilities.Chrome());_

but still get similiar errors:
_A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://selenoid:4444/wd/hub/session. The status of the exception was NameResolutionFailure, and the message was: An error occurred while sending the request. Couldn't resolve host name_

**Comment by Benny86** [comment]
@vania-pooh Do you have caught a time to take a look at it? Thanks.

**Comment by Benny86** [comment]
@vania-pooh Please take a look. Thanks.

**Comment by vania-pooh** [comment]
@Benny86 you have to start Selenoid-base container before the one you link it to.

**Comment by Benny86** [comment]
@vania-pooh I'm trying to add "-it selenoid/chrome" after the -p in jenkinsfile, but failed with invalid command line. and we also see "docker run ..." in pipeline to start container, not sure how to build selenoid-base container in current situations? Please specify. Thanks.

agent { 
	dockerfile  {
		  args '-u root:root -p 4444:4444 -it selenoid/chrome'
	}

**Comment by Benny86** [comment]
@vania-pooh I'm not familiar with this tool, not sure what's the correct/supported way to run selenoid, please give me much more details. Thanks.

**Comment by vania-pooh** [comment]
@Benny86 is it possible to just install Selenoid once to agents or to a separate VM and then just use a fixed URL is tests? E.g. you may have a host `selenoid.yourcompany.com` with Selenoid installed via `cm` tool. This usually takes 5 minutes to install. Then you just use: `http://selenoid.yourcompany.com:4444/wd/hub` in your tests. What you are trying to do in these issues is very strange and complicated.

**Comment by Benny86** [comment]
@vania-pooh @witkops 

As the manual one-time install Selenoid container on host is not acceptable by customer, I'm trying to move this one-time manual steps into my pipeline with auto steps every time. Here is my configurations:
Jenkinsfile:
pipeline { 
	agent none  

    stages{ 
       stage('Setting Up Selenoid Grid') { 
		agent { 
				docker  {
					image 'docker:latest' 
					 //the -v argument is to make docker inside docker container have enough privilege to run 
					 args '-u root:root -v "/var/run/docker.sock:/var/run/docker.sock:rw"' 
				} 
		  }
		  
          steps {     
			  try { 

				 sh "docker pull selenoid/chrome"
				 sh "docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release"
			   }  catch (Exception err) {
					echo 'selenoid already installed on host.'
			   }
			} 
       } 
       stage('Run Test') { 
		  agent { 
				docker  {
					image 'microsoft/dotnet'
					args '-u root:root'
				} 
		  }
		  
          steps { 
			sh 'pwd && ls && dotnet build && cd SM_Regression && dotnet test'
			} 
       }  
        
     } 
 } 
 
Currently, we can seet the selenoid container created but failed with browsers.json file doesn't exist. 
 ~$ docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                      PORTS                                                                      NAMES
3cddede29edd        microsoft/dotnet                   "cat"                    19 seconds ago      Up 17 seconds                                                                                          elegant_kilby
e904dfbaeee1        aerokube/selenoid:latest-release   "/usr/bin/selenoid -…"   29 seconds ago      Exited (1) 26 seconds ago                                                                              selenoid
~$ docker logs e904
2018/07/23 08:44:33 [-] [INIT] [Loading configuration files...]
2018/07/23 08:44:33 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]

Actually, I've manual add this file under /etc/selenoid/ and /usr/bin/selenoid/, but still failed to start with file not found error.
~$ cd /etc/selenoid
:/etc/selenoid$ ls
browsers.json
:/etc/selenoid$ cd /usr/bin/selenoid
:/usr/bin/selenoid$ ls
browsers.json

browsers.json setup as below:
{
        "chrome": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": "selenoid/chrome",
                "port": "4444",
                "path": "/"
            }
        }
    }
}


Not sure what's the root cause, do you have any ideas? Thanks.

**Comment by vania-pooh** [comment]
@Benny86 this file `browsers.json` should be mounted inside Docker container.

**Comment by Benny86** [comment]
@vania-pooh What do you mean? and How to do it?

**Comment by vania-pooh** [comment]
@Benny86 e.g. `docker run -v /dir/on/host/machine:/dir/inside/container ...`.

**Comment by Benny86** [comment]
@vania-pooh Why do I execute below 2 docker cmd on host directly, I don't have this browsers.json file issue, but issue existed when I docker run it on pipeline, 

sh "docker pull selenoid/chrome"
sh "docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release"

**Comment by vania-pooh** [comment]
@Benny86 probably because `pwd` means `current directory`. And on the pipeline this current directory does not contain `browsers.json`.

**Comment by Benny86** [comment]
@vania-pooh Finally, we run case passed with solenoid container by sidecar container, thanks for your kindly help here. 
node {
    checkout scm

	stage('Setup Selenoid container && run case') {

		echo 'Copy browsers.json file to workspace/config'
		sh "pwd && ls && cd SM_Regression/selenoidconfig && ls && sudo cp browsers.json ${WORKSPACE}/config/"

		docker.image('aerokube/selenoid:latest-release').withRun("--name selenoid -p 4444:4444 -u root:root -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config/:/etc/selenoid/:ro") { c ->
			echo 'hello world'
			sh "docker logs ${c.id}"
			docker.image('microsoft/dotnet').inside(" -u root:root --link ${c.id}:selenoid") {
				sh 'pwd && ls && dotnet build && cd SM_Regression && dotnet test'

}
}
}
}
