### ISSUE TITLE
Please add chrome 59

### ISSUE THREAD

**Issue by zero-master** [aerokube/selenoid-images#5]
Please add chrome 59

**Comment by vania-pooh** [comment]
@zero-master I don't see Debian packages yet. Should be available during next days. Then will certainly do.

**Comment by vania-pooh** [comment]
My previous statement was wrong. Will do today.

**Comment by vania-pooh** [comment]
Done. Please use `selenoid/chrome:59.0` and `selenoid/vnc:chrome_59.0` images respectively. Added image information to docs in https://github.com/aerokube/selenoid/pull/125.
