### ISSUE TITLE
Building the aerokube/selenoid and selenoid/vnc images

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/selenoid-images#65]
Hi,

I'm a newbie to Docker and I would like to apologize in advance if the following queries are too simple:

I work in a corporate environment where traffic out to the internet is highly restricted and thus we are not able to pull any images from the docker repository. As such, I will need to manually build the images myself.

Currently, we are using the following images:
- aerokube/selenoid:1.3.4
- selenoid/vnc:chrome_60.0
- selenoid/vnc:firefox_46.0

My goal would be to update them to the latest versions.

May I know if these are the appropriate github urls for them?

- aerokube/selenoid:1.3.4 (https://github.com/aerokube/selenoid-images/tree/master/selenium/base)
- selenoid/vnc:chrome_60.0 (https://github.com/aerokube/selenoid-images/tree/master/selenium/chrome)
- selenoid/vnc:firefox_46.0 (https://github.com/aerokube/selenoid-images/tree/master/selenium/firefox) 

I have also some questions related to the urls:
- How do I know if I should build either the 'local' or 'apt' folder of the chrome and firefox URLs?
- Do I need to build the 'Dockerfile.driver.tmpl' files for both browsers?
- For the 'base' folder, do I need to build both the Dockerfile in the 'base4' and the 'java' folder?

Thanks a lot!

**Comment by timothyjmtan** [comment]
I'm sorry, I just read the README.md.

Based on this line:
`Building procedure is automated with shell scripts selenium/build-dev.sh and selenium/build.sh that generate Dockerfile and then create browser and driver layers respectively. Before push each image is tested with these tests.`

Do I thus just need to checkout the entire repository, and just run both build-dev.sh and build.sh with the relevant arguments passed into them?

**Comment by vania-pooh** [comment]
@timothyjmtan see https://github.com/aerokube/selenoid-images#how-to-build-images-yourself.

**Comment by timothyjmtan** [comment]
Many thanks, @vania-pooh , for the new documentation. It is very clear and concise. I'll try it out and let you know.

**Comment by timothyjmtan** [comment]
Hello @vania-pooh , I did a 
`$ ./automate_chrome.sh 70.0.3538.67-1 2.43 70.0`

And I was stuck here:
`Step 1/4 : FROM selenoid/base:4.0`
`Trying to pull repository registry.access.redhat.com/selenoid/base ...`

I'm stuck here because I am unable to connect out into the internet to grab the image. I notice that the folder 'base/base_4' contains the image for `selenoid/base:4.0`, which is actually using `base:3.0`, and so on... till `base:1.0` is using `ubuntu:16.04`.

In my case, do I need to manually build all the base layers first in order to get a local version of 'base:4.0' to proceed?

**Comment by vania-pooh** [comment]
@timothyjmtan yes, just build `base/base_4` image.

**Comment by ruescar** [comment]
@vania-pooh I think it would be nice to add an example on how to build an image locally from the a browser deb package as opposed to use apt to the README file.

**Comment by vania-pooh** [comment]
@ruescar done.
