### ISSUE TITLE
Emoji is missing in chrome 70 image

### ISSUE THREAD

**Issue by Xotabu4** [aerokube/selenoid-images#68]
Seems like some fonts for emojis are missing:

In selenoid Chrome 70 container - 
![image](https://user-images.githubusercontent.com/3033972/48737707-6aa04b80-ec57-11e8-9864-b722884363f9.png)

In Ubuntu 18:
![image](https://user-images.githubusercontent.com/3033972/48737730-80157580-ec57-11e8-886a-7ff3c0406f03.png)

mac os:
![image](https://user-images.githubusercontent.com/3033972/48737746-886db080-ec57-11e8-9506-db59e36acbb4.png)

**Comment by Xotabu4** [comment]
Will try to build image with fonts, to be sure what should be included to docker image

**Comment by vania-pooh** [comment]
E.g. `fonts-emojione` package.
