### ISSUE TITLE
Non-latin symbols support

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid-images#8]
![955dcf95-73b2-4b6d-8fae-f1f6052b2831](https://user-images.githubusercontent.com/829320/27638114-c6f94e82-5c1a-11e7-8905-50b8a2e6d001.png)
With current images we get tofu instead of Chinese symbols.

**Comment by ikuznechikova** [comment]
![2017-06-30_1126](https://user-images.githubusercontent.com/9205298/27727790-a56f8a78-5d88-11e7-80de-98264508b62c.png)
I have a problem not only with Chinese, but also with Korean, Chinese, Arabic symbols. Reproduced in all versions Selenoid(firefox, chrome, opera)

**Comment by vania-pooh** [comment]
Ok, will take a look during the weekend.

**Comment by vania-pooh** [comment]
Found an easy solution: need to install one more fonts package `fonts-noto-cjk`. The only issue is - installing this package adds 100 Mb of fonts. Investigating how to obtain the same result spending less disk space.

**Comment by vania-pooh** [comment]
An alternative Chinese fonts are in package `fonts-wqy-zenhei` (17 Mb).

**Comment by vania-pooh** [comment]
Created 2 images: `vaniapooh/firefox:54.0_noto` and `vaniapooh/firefox_54.0_zenhei`.

**Comment by ikuznechikova** [comment]
> vania-pooh commented 4 days ago
> Created 2 test images: vaniapooh/firefox:54.0_noto and vaniapooh/firefox:54.0_zenhei.


![image](https://user-images.githubusercontent.com/9205298/28059826-2060cb54-662e-11e7-9f20-dd5cbe962782.png)

Vanya, thank you! Now that's better, but add a display of Thai symbols, please.

**Comment by vania-pooh** [comment]
@ikuznechikova thai still does not work even with `noto` image?

**Comment by ikuznechikova** [comment]
Unfortunately, thai symbols doesn't work neither in ```noto``` nor in ```zenhei``` images. See screenshot above.

**Comment by vania-pooh** [comment]
Ok, will check that.

**Comment by vania-pooh** [comment]
@ikuznechikova In order to support Thai we need to install `fonts-thai-tlwg-ttf` package (adds 8 megabytes to image). Please test with the following image: `vaniapooh/firefox:54.0_zenhei_thai` - it contains both Chinese and Thai support.

**Comment by ikuznechikova** [comment]
@vania-pooh , thank you very much! Now all the necessary symbols (Chinese, Thai, Korean) are displayed in the browser of the image: ```vaniapooh/firefox:54.0_zenhei_thai```
![lang](https://user-images.githubusercontent.com/9205298/28666549-765e0630-72d0-11e7-9e22-d52f9d627cc3.png)

**Comment by vania-pooh** [comment]
Good. Will need to apply these changes to all images.

**Comment by trysh** [comment]
thank you !
When to apply these changes to all images (selenoid/chrome selenoid/firefox ...)?

**Comment by vania-pooh** [comment]
We are currently thinking about one more improvement related to logging. Will update this issue when this is done. Updating all 100+ images is a lot of work and will cause users to redownload a lot of stuff. We should think a bit more before doing such changes.

**Comment by vania-pooh** [comment]
While waiting for this issue to be fixed here is an example Dockerfile how to customize fonts:
```
FROM selenoid/vnc:firefox_54.0

RUN \
    apt-get update && \
    apt-get -y --no-install-recommends install fonts-wqy-zenhei fonts-thai-tlwg-ttf && \
    apt-get clean && \
    rm -Rf /tmp/*
```

**Comment by vania-pooh** [comment]
Possible Japanese font packages: `onts-ipafont-mincho fonts-ipafont-gothic`.

**Comment by vania-pooh** [comment]
Pushed an example image of what I would like to add to all browser images - `vaniapooh/firefox:56.0`. It includes fonts as well as encodings. Please test whether fonts are OK.

**Comment by ikuznechikova** [comment]
It was checked the display of non-Latin (Korean, Thai, Chinese, Japanese) characters in the image ```vaniapooh/firefox:56.0```, the test ok
![image](https://user-images.githubusercontent.com/9205298/32490140-393a05ee-c3c3-11e7-9447-9582354bb0e1.png)

![image](https://user-images.githubusercontent.com/9205298/32490254-8ea95caa-c3c3-11e7-9a6c-a33920601f88.png)

**Comment by vania-pooh** [comment]
@ikuznechikova ok, will prepare more images.

**Comment by Arslanbekov** [comment]
@vania-pooh hi, no news? We are really looking forward to :)

**Comment by vania-pooh** [comment]
@Arslanbekov will start rebuilding today. Which browsers are more important? I could e.g. first of all rebuild all Chrome or Firefox images.

**Comment by Arslanbekov** [comment]
The most necessary - chrome

**Comment by vania-pooh** [comment]
Agreed.

**Comment by vania-pooh** [comment]
Forgot to add hindi fonts. Possible solution - `fonts-deva`.

**Comment by vania-pooh** [comment]
After a month of intensive work this is finally fixed. All images are supporting new fonts and video recording.
