### ISSUE TITLE
Add ability to run Google Chrome without Xvfb in Docker container.

### ISSUE THREAD

**Issue by janeberets** [aerokube/selenoid-images#9]
Now it is not possible to run Google Chrome headless without Xvfb in Docker . But since version 59 Chrome can be used with option `--headless`. 
I think that container without Xvfb and with non GUI Chrome will use less resources, and test will be faster.

**Comment by vania-pooh** [comment]
Created `vaniapooh/chrome:59.0-headless`. How to launch:
```
final DesiredCapabilities browser = new DesiredCapabilities("chrome", "59.0", Platform.LINUX);
        browser.setCapability("chromeOptions", new HashMap<String, Object>(){
            {
                put("args", new ArrayList<String>(){
                    {
                        add("headless");
                    }
                });
            }
        });
```
This image still contains Xvfb binaries, but they are not launched. As a second step can try to completely remove Xvfb.

**Comment by vania-pooh** [comment]
@janeberets any more stuff to investigate here?

**Comment by janeberets** [comment]
@vania-pooh No, thank You.
