### ISSUE TITLE
chrome 71.0 and xvfb trying to bind ipv6

### ISSUE THREAD

**Issue by djordje-petrovic** [aerokube/selenoid-images#92]
Hi.

This line here:
https://github.com/aerokube/selenoid-images/blob/master/selenium/chrome/entrypoint.sh#L45
tells xvfb to listen on tcp. This means it will try to listen on ipv6 also. In my case container is without it and due to that it fails binding the ip with this error:

`[1548681455.927][SEVERE]: CreatePlatformSocket() returned an error, errno=0: Address family not supported by protocol (97)
[1548681455.927][INFO]: listen on IPv6 failed with error ERR_ADDRESS_UNREACHABLE`

Since it's not possible to tell xvfb not to listen on ipv6 (as long as I'm aware) what can I do to resolve this issue? Is the Chrome headless only way to go or is there some other workaround?

**Comment by vania-pooh** [comment]
@djordje-petrovic at least without `-listen tcp` flag video recording will not work. What is your operation system?

**Comment by djordje-petrovic** [comment]
@vania-pooh It's Ubuntu 18.04.1 LTS

**Comment by djordje-petrovic** [comment]
@vania-pooh Ok. I think i found a workaround, kinda savage but it looks like it's gonna work:

`/usr/bin/xvfb-run -l -n "$DISPLAY_NUM" -s "-ac -screen 0 $SCREEN_RESOLUTION -noreset -listen tcp" /usr/bin/wmwait /usr/bin/chromedriver --port=4444 --whitelisted-ips='' ${DRIVER_ARGS} || true &
XVFB_PID=$!`

Adding` || true` at the end of that line which throws error. However for this i need to rebuild docker image. So I've tried:

`./automate_chrome.sh 71.0.3578.98-1 2.45 71.0`

But there is an issue:

`Step 1/4 : FROM selenoid/base:4.0_devtools
manifest for selenoid/base:4.0_devtools not found`

Image with that tag doesn't exist. I've tried building with base:4.0 but then wmwait binary is missing?
Do I have to compile it?

**Comment by vania-pooh** [comment]
@djordje-petrovic use tag [3.0.0](https://github.com/aerokube/selenoid-images/releases/tag/3.0.0) of this repository, i.e.:
```
$ git chekout 3.0.0
```

**Comment by djordje-petrovic** [comment]
@vania-pooh In the end I've just enabled ipv6 in grub and everything seems to work.
Thanks for the help.

**Comment by vania-pooh** [comment]
@djordje-petrovic great!
