### ISSUE TITLE
v3.0.0 automate_chrome.sh missing parameter <browser_version>

### ISSUE THREAD

**Issue by NikolayMakhonin** [aerokube/selenoid-images#95]
I have created the .deb package of chromium 33.0
I am trying to create a docker image using this command:
```./automate_chrome.sh ../../browsers/chromium33.deb 2.10 33.0```

The script ends on the following log lines:
```...
+ pushd chrome
~ / dev / selenoid-images / selenium / chrome ~ / dev / selenoid-images / selenium
+ ../build.sh chromedriver 2.10 selenoid / chrome: 33.0
Usage: build.sh {chromedriver | operadriver | selenoid | selenium} <browser_version> <driver_or_selenium_version> <tag> [<<supplementary_version>]
```

There is missing the <browser_version> parameter. As I understand it, the script should pass the path to my .deb package with the browser.

**Comment by vania-pooh** [comment]
Package name should contain Chrome version, e.g. `google-chrome-stable_48.0.2564.109-1+aerokube0_amd64.deb `. This is a standard Debian package name notation.
