### ISSUE TITLE
Android: Unable to set MobileCapabilityType.BROWSER_NAME

### ISSUE THREAD

**Issue by DmitriyVasilyevPRV** [aerokube/selenoid-images#98]
Appium requries one of the following params in desired capabilities:
`The desired capabilities must include either an app, appPackage or browserName`
The problem arises with `browserName`

According to appium doc http://appium.io/docs/en/writing-running-appium/caps/

browserName can be one of following 'Safari' for iOS and 'Chrome', 'Chromium', or 'Browser' for Android

Now imagine case:
User uses selenide and specifies 
`capabilities.setBrowserName("android");`
`capabilities.setVersion("8.1");`

Selenide uses browser.json to determine container for "android" and run appium.

Problem is, that setBrowserName is equals to 
`capabilities.setCapability("browserName", "android");`
which is also equals to
`capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Chrome");`
because MobileCapabilityType.BROWSER_NAME inherited from CapabilityType and equals "browserName".

So as a result, appium will receive capability equals to 
`capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "android");`
which will result in error on appium side
`Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app, appPackage or browserName`
because appium can receive only 'Safari' for iOS and 'Chrome', 'Chromium', or 'Browser' for Android values.

Im not sure that this can/need to be fixed, but need advice on how to pass this value to appium via selenoid in desired capabilities

Generic case is: i want to test web application in android browser

**Comment by DmitriyVasilyevPRV** [comment]
Sorry, lack of documentation(((
Figure it out

**Comment by mikk150** [comment]
I would like to figure it out...

**Comment by vania-pooh** [comment]
@mikk150 for Android application testing should use the following combination of capabilities:
```
deviceName = android # Instead of browser name
app = http://your-ci.example.com/your-app.apk
appPackage = com.example.yourapp
appActivity = com.example.yourapp.MainActivity
```
